INSERT INTO TipoViolazione (Descrizione, IdVerbale)
VALUES
('Atti osceni in luogo pubblico', 28),
('Eccesso di velocità', 29),
('Sosta vietata', 30),
('Rumori molesti', 31),
('Occupazione abusiva di spazi pubblici', 32),
('Affissioni abusive', 33),
('Commercio abusivo', 34),
('Mendicita molesta', 35),
('Detenzione o uso di sostanze stupefacenti', 36),
('Ubriachezza pubblica', 37),
('Accattonaggio aggressivo', 38),
('Violazione delle norme sanitarie', 39),
('Trasporto irregolare di rifiuti', 40),
('Inosservanza delle norme su animali domestici', 41),
('Vandalismo', 42),
('Rapina a mano armata', 43),
('Assalto a pubblico ufficiale', 44),
('Troppe carezze', 45);